Repository NurOrNuLL/ESDP-AP-5-6-TEAM-2, pull requests merged in 2022-07, with the labels that each got.

#588 feat: Исключил возможность редактирования ИИН/БИН контрагента
  infrastructure/web/contractor/forms.py
  infrastructure/web/contractor/views.py
  infrastructure/web/templates/contractor/contractor_update_compare.html
  infrastructure/web/templates/contractor/update.html
  services/contractor_services.py
  services/tests/test_contractor_services.py
Labels: to do, enhancement

#597 568 скрыть кнопки на которых у пользователей нет прав
  core/settings.py
  infrastructure/web/employee/context_processor.py
  infrastructure/web/nomenclature/views.py
  infrastructure/web/static/js/own/own_list.js
  infrastructure/web/templates/contractor/contractor_detail.html
  infrastructure/web/templates/employee/employee_detail.html
  infrastructure/web/templates/nomenclature/list.html
  infrastructure/web/templates/order/order_detail.html
  infrastructure/web/templates/partials/sidebar.html
  infrastructure/web/templates/trade_point/trade_points.html
Labels: to do

#598 fix: Исправил конкурентное редактирование заказ наряда
  infrastructure/web/order/views.py
  infrastructure/web/templates/order/concurrency_update.html
Labels: bug fix

#613 583 реализовать создание очереди
  infrastructure/web/contractor/forms.py
  infrastructure/web/contractor/views.py
  infrastructure/web/queue/__init__.py
  infrastructure/web/queue/forms.py
  infrastructure/web/queue/serializers.py
  infrastructure/web/queue/views.py
  infrastructure/web/static/js/queue/queue_create.js
  infrastructure/web/templates/partials/queue/queue_form.html
  infrastructure/web/templates/partials/sidebar.html
  infrastructure/web/templates/queue/queue_create.html
  infrastructure/web/urls.py
  models/queue/admin.py
  models/queue/migrations/0003_queue_trade_point_alter_queue_contractor.py
  models/queue/models.py
  services/queue_services.py
Labels: enhancement

#615 fix: Исправил ошибки
  infrastructure/web/queue/views.py
Labels: bug fix

#617 мастер дев 56
  core/settings.py
  infrastructure/web/context_processor.py
  infrastructure/web/contractor/forms.py
  infrastructure/web/contractor/views.py
  infrastructure/web/queue/__init__.py
  infrastructure/web/queue/forms.py
  infrastructure/web/queue/serializers.py
  infrastructure/web/queue/views.py
  infrastructure/web/report/consumers.py
  infrastructure/web/static/js/queue/queue_create.js
  infrastructure/web/templates/partials/queue/queue_form.html
  infrastructure/web/templates/partials/sidebar.html
  infrastructure/web/templates/queue/queue_create.html
  infrastructure/web/urls.py
  models/queue/migrations/0003_queue_trade_point_alter_queue_contractor.py
  services/employee_services.py
  services/queue_services.py
Labels: celery

#618 мастер дев 57
  models/queue/admin.py
  models/queue/models.py
Labels: celery

#625 fix: Убрать возможность менять статус оплаты из админки
  models/order/admin.py
  models/payment/admin.py
Labels: to do

#628 627 Исправить ошибки вывода формы при создании контрагента
  infrastructure/web/contractor/forms.py
  infrastructure/web/contractor/views.py
  infrastructure/web/static/js/contractor/contractor_create.js
  infrastructure/web/templates/partials/contractor/contractor_form.html
  models/contractor/migrations/0011_alter_contractor_bic_alter_contractor_iic.py
  models/contractor/models.py
Labels: bug fix

#632 feat: Добавил валидацию для json поля доверенного лица при создании и…
  infrastructure/web/contractor/views.py
  models/contractor/validators.py
Labels: enhancement

#636 feat: Реализовал обновлённую логику скачивания отчёта в Excel файл
  infrastructure/web/static/js/report/report_create.js
  services/report_services.py
Labels: enhancement

#637 479 реализовать редактирование собственности с оптимистичной блокировкой параллельных запросов
  infrastructure/web/own/serializer.py
  infrastructure/web/own/views.py
  infrastructure/web/static/js/own/own_full_list.js
  infrastructure/web/static/js/own/own_list.js
  infrastructure/web/templates/own/owns.html
  infrastructure/web/templates/partials/own/own_update.html
  infrastructure/web/urls.py
  models/own/migrations/0006_own_version.py
  models/own/models.py
  services/own_services.py
Labels: to do, enhancement

#638 fix: Добавил миграцию для собственности
  models/own/migrations/0007_merge_0006_own_is_deleted_0006_own_version.py
Labels: bug fix

#655 480 написать тест на оптимистичную блокировку параллельного обновления собственности
  infrastructure/web/own/tests/__init__.py
  infrastructure/web/own/tests/test_own_views.py
Labels: to do

#666 fix: Исправить ошибку при редактировании сотрудников
  infrastructure/web/employee/views.py
Labels: bug fix

#668 мастер дев 65
  celery.sh
  core/settings.py
  data/fixtures/dump.json
  infrastructure/web/employee/views.py
Labels: celery

#683 fix: Исправил мелкие ошибки
  infrastructure/web/static/js/own/own_full_list.js
  infrastructure/web/templates/base.html
  infrastructure/web/templates/contractor/update.html
  infrastructure/web/templates/home.html
  infrastructure/web/templates/nomenclature/list.html
  infrastructure/web/templates/nomenclature/nomenclature_create.html
  infrastructure/web/templates/order/order_create.html
  infrastructure/web/templates/order/order_create_stage1.html
  infrastructure/web/templates/order/order_create_stage2.html
  infrastructure/web/templates/order/order_create_stage3.html
  infrastructure/web/templates/order/order_create_stage4.html
  infrastructure/web/templates/order/update.html
  infrastructure/web/templates/own/own_create.html
  infrastructure/web/templates/partials/sidebar.html
  infrastructure/web/templates/queue/queue_create.html
  infrastructure/web/templates/registration/login.html
  infrastructure/web/templates/registration/register.html
  infrastructure/web/templates/report/report.html
  infrastructure/web/templates/report/report_detail.html
  infrastructure/web/templates/report/report_list.html
  infrastructure/web/templates/trade_point/trade_point_create.html
  infrastructure/web/templates/trade_point/trade_point_update.html
  infrastructure/web/templates/trade_point/trade_points.html
  logs.log
  models/contractor/validators.py
Labels: bug fix

#688 feat: Реализовал логику скачивания по утверждённому формату отчёта в …
  infrastructure/web/report/views.py
  services/report_services.py
Labels: enhancement

#686 682 исправление мелких ошибок
  infrastructure/web/own/tests/test_own_views.py
  infrastructure/web/own/views.py
  infrastructure/web/static/js/own/own_full_list.js
Labels: bug fix

#689 мастер дев 72
  infrastructure/web/own/tests/test_own_views.py
  infrastructure/web/own/views.py
  infrastructure/web/report/views.py
  infrastructure/web/static/js/own/own_full_list.js
  logs.log
  services/report_services.py
Labels: celery

#691 мастер дев 73
  logs.log
Labels: celery
