Repository NurOrNuLL/ESDP-AP-5-6-TEAM-2, pull requests merged in 2022-06, with the labels that each got.

#225 feat: Реализовал частичное создание заказ-наряда
  infrastructure/web/contractor/views.py
  infrastructure/web/order/forms.py
  infrastructure/web/order/serializers.py
  infrastructure/web/order/views.py
  infrastructure/web/templates/contractor/contractor_detail.html
  infrastructure/web/templates/order/order_create.html
  infrastructure/web/templates/partials/order/order_form.html
  infrastructure/web/urls.py
  models/order/migrations/0003_alter_order_status.py
  models/order/models.py
  models/payment/admin.py
  models/payment/migrations/0003_rename_status_payment_payment_status.py
  models/payment/migrations/0004_alter_payment_payment_status.py
  models/payment/models.py
  services/contractor_services.py
  services/order_services.py
  services/own_services.py
  services/payment_services.py
  services/trade_point_services.py
Labels: to do, enhancement

#232 feat: Реализовал частичную детальную страницу Заказ-наряда
  infrastructure/web/contractor/views.py
  infrastructure/web/order/views.py
  infrastructure/web/templates/contractor/contractor_detail.html
  infrastructure/web/templates/order/order_detail.html
  infrastructure/web/urls.py
  models/payment/admin.py
  models/payment/migrations/0005_alter_payment_type.py
  models/payment/migrations/0006_rename_type_payment_details.py
  models/payment/models.py
  models/payment/validators.py
  services/order_services.py
Labels: to do, enhancement

#237 feat: Написал тест по заказ-наряду
  services/tests/test_order_services.py
Labels: to do, enhancement

#242 feat: Написать тесты на сервисы моделей торговой точки
  services/tests/test_trade_point_services.py
Labels: to do

#269 feat: Написал тесты на все сервисы модели заказ-наряда
  services/order_services.py
  services/tests/test_order_services.py
Labels: to do, enhancement

#272 refactor: Создал миграцию
  models/own/migrations/0003_own_is_part.py
Labels: to do

#279 feat: Разделил собственность контрагента на автомобили и запчасти (де…
  infrastructure/web/static/js/own/own_create.js
  infrastructure/web/templates/contractor/contractor_detail.html
  infrastructure/web/templates/own/own_create.html
  infrastructure/web/templates/partials/own/own_form.html
  services/own_services.py
  services/tests/test_own_services.py
Labels: to do, enhancement

#280 fix: Исправить баг при создании мастера
  infrastructure/web/employee/views.py
  infrastructure/web/templates/employee/employee_create.html
  infrastructure/web/templates/partials/employee/employee_form.html
  infrastructure/web/templates/registration/register.html
Labels: bug fix

#292 fix: Реализовал пессимистичную блокировку для параллельного обновления данных контрагента
  infrastructure/web/contractor/views.py
  services/contractor_services.py
Labels: to do, enhancement

#294 293 Исправил форму создания собственности
  .gitignore
  infrastructure/web/own/views.py
  infrastructure/web/templates/contractor/contractor_detail.html
  infrastructure/web/templates/partials/own/own_form.html
Labels: to do, bug fix

#300 мастер 4
  .github/workflows/docker_hub.yml
Labels: pushHub

#323 feat: Изменил модель и форму собственнности
  infrastructure/web/own/views.py
  infrastructure/web/static/js/own/own_create.js
  infrastructure/web/templates/own/own_create.html
  infrastructure/web/templates/partials/own/own_form.html
  models/contractor/migrations/0004_alter_contractor_trust_person.py
  models/contractor/models.py
  models/own/admin.py
  models/own/models.py
  services/own_services.py
  services/tests/test_own_services.py
Labels: to do, enhancement

#335 fix: Подкорректировать детальную страницу контрактора
  infrastructure/web/static/css/style.css
  infrastructure/web/static/js/own/own_delete.js
  infrastructure/web/templates/contractor/contractor_detail.html
Labels: to do, bug fix

#346 fix: Отредактировать страницу детального просмотра заказ-наряда
  infrastructure/web/templates/contractor/contractor_detail.html
  infrastructure/web/templates/order/order_detail.html
Labels: bug fix

#363 311 Применить оптимистик лок для редактирования контрактора
  infrastructure/web/contractor/views.py
  infrastructure/web/templates/contractor/contractor_update_compare.html
  infrastructure/web/templates/contractor/update.html
  infrastructure/web/urls.py
  models/contractor/migrations/0005_contractor_version.py
  models/contractor/models.py
  requirements.txt
  services/contractor_services.py
  services/tests/test_contractor_services.py
Labels: to do, enhancement

#400 мастер дев 20
  core/settings.py
Labels: celery

#409 мастер дев 22
  .github/workflows/docker_hub.yml
  .github/workflows/docker_hub_celery.yml
Labels: celery

#414 мастер дев 24
  .github/workflows/docker_hub.yml
  .github/workflows/docker_hub_celery.yml
  core/celery.py
  core/settings.py
  infrastructure/accounts/views.py
  infrastructure/web/employee/forms.py
  infrastructure/web/employee/tasks.py
  infrastructure/web/employee/views.py
  infrastructure/web/static/img/favicon.ico
  infrastructure/web/templates/base.html
  infrastructure/web/templates/employee/employee_create.html
  infrastructure/web/templates/employee/employee_detail.html
  infrastructure/web/templates/employee/employee_update.html
  infrastructure/web/templates/employee/employee_update_conflict.html
  infrastructure/web/templates/partials/employee/employee_form.html
  infrastructure/web/urls.py
  models/employee/migrations/0003_alter_employee_image.py
  models/employee/migrations/0004_employee_version.py
  models/employee/models.py
  nginx/default.conf
  services/employee_services.py
  services/trade_point_services.py
Labels: celery

#419 407 доработать action на проверку тестов и ci на пуш образов
  .github/workflows/docker_hub.yml
  .github/workflows/docker_hub_celery.yml
Labels: celery

#420 мастер дев 26
  .github/workflows/docker_hub.yml
  .github/workflows/docker_hub_celery.yml
  infrastructure/web/nomenclature/tasks/export_exel.py
  infrastructure/web/nomenclature/tests/__init__.py
  infrastructure/web/nomenclature/tests/test_nomenclature_tasks.py
Labels: celery

#422 мастер дев 27
  .github/workflows/docker_hub_celery.yml
Labels: pull request celery

#425 мастер дев 28
  .github/workflows/docker_hub.yml
  .github/workflows/docker_hub_celery.yml
  infrastructure/web/employee/views.py
  infrastructure/web/templates/employee/employee_detail.html
  infrastructure/web/templates/partials/employee/employee_form.html
Labels: pull request celery

#427 мастер дев 29
  .github/workflows/docker_hub_celery.yml
  services/trade_point_services.py
Labels: pull request celery

#429 мастер дев 30
  .github/workflows/docker_hub_celery.yml
  infrastructure/web/templates/employee/employee_detail.html
  infrastructure/web/templates/partials/employee/employee_form.html
  services/trade_point_services.py
Labels: pull request celery

#431 мастер дев 31
  .github/workflows/docker_hub_celery.yml
  infrastructure/web/templates/employee/employee_detail.html
Labels: pull request celery

#433 мастер дев 32
  .github/workflows/docker_hub_celery.yml
  infrastructure/web/templates/employee/employee_detail.html
Labels: pull request celery

#435 мастер дев 33
  .github/workflows/docker_hub_celery.yml
Labels: pull request celery

#452 мастер дев 37
  .github/workflows/docker_hub_celery.yml
  infrastructure/web/static/css/admin.css
  models/employee/models.py
  templates/admin/base_site.html
Labels: celery

#454 мастер дев 38
  .github/workflows/docker_hub_celery.yml
  .github/workflows/test.yml
  infrastructure/web/employee/views.py
Labels: celery

#458 feat: Написал тест на оптимистичную блокировку параллельных запросов …
  infrastructure/web/trade_point/tests/__init__.py
  infrastructure/web/trade_point/tests/test_trade_point.py
  infrastructure/web/trade_point/views.py
Labels: to do, enhancement

#464 442 сделать отправку фотографии на aws s3 без локального сохранения
  infrastructure/accounts/views.py
  infrastructure/web/employee/tasks.py
  infrastructure/web/employee/views.py
  infrastructure/web/templates/employee/employee_create.html
  infrastructure/web/templates/employee/employee_detail.html
  infrastructure/web/templates/registration/register.html
  models/employee/migrations/0006_alter_employee_image.py
  models/employee/models.py
  services/employee_services.py
Labels: bug fix

#487 fix: Изменить модель и создание филиала
  infrastructure/web/static/js/bootstrap-select.min.js
  infrastructure/web/templates/partials/trade_point/trade_point_form.html
  infrastructure/web/trade_point/views.py
  models/trade_point/admin.py
  models/trade_point/migrations/0004_remove_tradepoint_nomenclature_and_more.py
  models/trade_point/migrations/0005_alter_tradepoint_nomenclature.py
  models/trade_point/models.py
  services/trade_point_services.py
Labels: bug fix

#490 refactor: Произвёл коррекцию страницы редактирования контрагента
  infrastructure/web/templates/contractor/update.html
Labels: to do, bug fix

#494 refactor: Произвёл коррекцию детальной страницы контрагента
  infrastructure/web/static/js/own/own_delete.js
  infrastructure/web/templates/contractor/contractor_detail.html
Labels: to do, bug fix

#496 refactor: Произвёл коррекцию страницы списка сотрудников
  infrastructure/web/static/js/employee/employee_view.js
  infrastructure/web/templates/employee/employees.html
Labels: to do, bug fix

#495 fix: Изменить редактирование филиала
  infrastructure/web/templates/trade_point/trade_point_update.html
  infrastructure/web/templates/trade_point/trade_point_update_compare.html
  infrastructure/web/trade_point/tests/test_trade_point.py
  infrastructure/web/trade_point/views.py
  services/trade_point_services.py
Labels: bug fix

#497 fix: Написать валидацию на ввод логина и пароля при создании аккаунта
  infrastructure/accounts/forms.py
  infrastructure/accounts/validators.py
  infrastructure/web/templates/registration/register.html
Labels: bug fix

#500 481 написать валидацию на ввод логина и пароля при создании аккаунта
  infrastructure/accounts/forms.py
  infrastructure/accounts/validators.py
  infrastructure/web/templates/registration/register.html
Labels: bug fix

#502 fix: Коррекция страницы списка заказ-нарядов
  infrastructure/web/templates/home.html
Labels: bug fix

#503 fix: Подкорректировать детальную страницу сотрудника
  infrastructure/web/employee/views.py
  infrastructure/web/templates/employee/employee_detail.html
  infrastructure/web/templates/partials/employee/image_modal.html
Labels: to do, bug fix

#509 fix: Коррекция создания сотрудника
  infrastructure/accounts/views.py
  infrastructure/web/static/css/style.css
  infrastructure/web/templates/employee/employee_create.html
  infrastructure/web/templates/employee/employee_detail.html
  infrastructure/web/templates/employee/employee_update.html
  infrastructure/web/templates/partials/employee/employee_form.html
  infrastructure/web/templates/registration/register.html
  requirements.txt
Labels: to do, bug fix

#516 feat: Написать валидацию на ввод ИИН сотрудника по дате рождения
  infrastructure/accounts/views.py
  infrastructure/web/employee/views.py
  infrastructure/web/templates/employee/employee_detail.html
  infrastructure/web/templates/employee/employee_update.html
  models/employee/migrations/0007_alter_employee_iin.py
  models/employee/migrations/0008_alter_employee_iin.py
  models/employee/migrations/0009_alter_employee_iin.py
  models/employee/models.py
  models/employee/validators.py
Labels: to do, enhancement

#518 472 реализовать редактирование номенклатуры с оптимистичной блокировкой параллельных запросов
  infrastructure/web/static/js/nomenclature/nomenclature_update.js
  infrastructure/web/templates/nomenclature/partial/nomenclature_update.html
Labels: bug fix

#531 477 написать валидацию на ввод иин сотрудника по дате рождения
  infrastructure/web/employee/views.py
  infrastructure/web/templates/partials/employee/employee_form.html
  models/contractor/migrations/0006_alter_contractor_bic_alter_contractor_iin_or_bin.py
  models/contractor/migrations/0007_alter_contractor_iic.py
  models/contractor/migrations/0008_alter_contractor_bic_alter_contractor_iic.py
  models/contractor/migrations/0009_alter_contractor_bic_alter_contractor_iic.py
  models/contractor/migrations/0010_alter_contractor_name.py
  models/contractor/models.py
  models/contractor/validators.py
  models/employee/migrations/0010_alter_employee_name_alter_employee_phone_and_more.py
  models/employee/models.py
  models/employee/validators.py
  requirements.txt
Labels: bug fix

#538 477 написать валидацию на ввод иин сотрудника по дате рождения
  models/contractor/migrations/0010_alter_contractor_name.py
  models/contractor/models.py
  models/contractor/validators.py
  models/employee/migrations/0010_alter_employee_name_alter_employee_phone_and_more.py
  models/employee/models.py
  models/employee/validators.py
  services/employee_services.py
Labels: bug fix

#548 мастер дев 54
  infrastructure/web/static/js/report/report_task_ajax.js
  requirements.txt
Labels: celery

#570 fix: Убрать кнопку детали контрагента в списке собственностей
  infrastructure/web/static/js/own/own_full_list.js
  infrastructure/web/templates/own/owns.html
Labels: bug fix

#575 fix: Поменять редирект на список филиалов при создании филиала
  infrastructure/web/trade_point/views.py
Labels: bug fix

#587 feat: Реализовал скачивание отчётов Excel файлом
  infrastructure/web/report/forms.py
  infrastructure/web/report/views.py
  infrastructure/web/static/js/report/report_task_ajax.js
  infrastructure/web/templates/report/report.html
  infrastructure/web/urls.py
  services/report_services.py
Labels: to do, enhancement
