Repository NurOrNuLL/ESDP-AP-5-6-TEAM-2, pull requests merged in 2022-05, with the labels that each got.

#17 Шаблоны для issue и pull request
  docs/issue_template.md
  docs/pull_request_template.md
Labels: enhancement

#18 feat: Добавить шаблон тикета
  docs/issue_template.md
Labels: docs

#19 Шаблон пул реквеста
  docs/pull_request_template.md
Labels: docs

#20 Шаблоны тикета и пул реквеста
  docs/issue_template.md
  docs/pull_request_template.md
Labels: docs

#31 Файл docker-compose
  docker-compose.yml
Labels: to do

#32 Добавил файл docker-compose
  .github/workflows/flake8.yml
  docker-compose.yml
  requirements.txt
Labels: to do

#113 feat: Реализовал список контрагентов
  infrastructure/web/contractor/views.py
  infrastructure/web/templates/contractor/contractors.html
  infrastructure/web/templates/partials/sidebar.html
  infrastructure/web/urls.py
  services/contractor_services.py
Labels: to do, enhancement

#114 feat: Реализовал детальный просмотр страницы контрагента
  infrastructure/web/contractor/views.py
  infrastructure/web/templates/contractor/contractor_detail.html
  infrastructure/web/templates/contractor/contractors.html
  infrastructure/web/urls.py
  services/contractor_services.py
  services/organization_services.py
Labels: to do, enhancement

#125 123 Доработал форму создания контрагента
  infrastructure/web/contractor/views.py
  infrastructure/web/service/forms.py
  infrastructure/web/templates/contractor/contractor_create.html
  infrastructure/web/templates/contractor/contractor_detail.html
  infrastructure/web/templates/partials/contractor/contractor_form.html
  infrastructure/web/trade_point/forms.py
  services/contractor_services.py
Labels: to do, bug fix

#148 feat: Изменил модель контрагента
  models/contractor/admin.py
  models/contractor/models.py
Labels: to do, enhancement

#166 feat: Создать модель сотрудников
  models/employee/__init__.py
  models/employee/admin.py
  models/employee/migrations/__init__.py
  models/employee/models.py
  models/employee/validators.py
Labels: to do

#169 164 создать модель сотрудников
  core/settings.py
  models/employee/migrations/0001_initial.py
Labels: bug fix

#173 feat: Создать модель кастомного пользователя
  core/settings.py
  data/fixtures/auth.json
  infrastructure/accounts/admin.py
  infrastructure/accounts/migrations/0001_initial.py
  infrastructure/accounts/models.py
  models/employee/admin.py
  models/employee/models.py
Labels: to do

#176 164 создать модель сотрудников
  infrastructure/accounts/admin.py
  infrastructure/accounts/migrations/0002_rename_id_customuser_uuid.py
  infrastructure/accounts/models.py
  models/employee/admin.py
  models/employee/migrations/0002_remove_employee_id_employee_uuid.py
  models/employee/models.py
Labels: bug fix

#177 164 создать модель сотрудников
  core/settings.py
  core/storage_backends.py
  models/employee/models.py
Labels: bug fix

#178 164 создать модель сотрудников
  requirements.txt
Labels: bug fix

#179 fix: Отредактировал вывод данных на странице создания контрагента
  infrastructure/web/contractor/views.py
  infrastructure/web/static/js/contractor/contractor_create.js
  infrastructure/web/templates/contractor/contractor_create.html
  infrastructure/web/templates/partials/contractor/contractor_form.html
  services/organization_services.py
Labels: to do, bug fix

#181 feat: Реализовать создание сотрудников
  infrastructure/web/employee/__init__.py
  infrastructure/web/employee/forms.py
  infrastructure/web/employee/views.py
  infrastructure/web/templates/employee/employee_create.html
  infrastructure/web/templates/partials/employee/employee_form.html
  infrastructure/web/templates/partials/sidebar.html
  infrastructure/web/urls.py
  models/employee/migrations/0003_alter_employee_tradepoints.py
  services/employee_services.py
Labels: to do

#189 fix: Перенести статические файлы с aws s3 в проект
  core/settings.py
  core/storage_backends.py
  infrastructure/web/contractor/views.py
  pdf/AUTH_RSA256_a84da4bea3ff55a07c99ed84e33a095d935f899f.p12
Labels: bug fix

#198 feat: Написать модель способа оплаты
  core/settings.py
  models/payment_method/__init__.py
  models/payment_method/admin.py
  models/payment_method/migrations/0001_initial.py
  models/payment_method/migrations/__init__.py
  models/payment_method/models.py
Labels: to do, enhancement

#202 199 Написать модель оплаты
  core/settings.py
  models/payment/__init__.py
  models/payment/admin.py
  models/payment/migrations/0001_initial.py
  models/payment/migrations/__init__.py
  models/payment/models.py
Labels: to do, enhancement

#203 fix: Написал модель заказ-наряда
  core/settings.py
  models/order/__init__.py
  models/order/admin.py
  models/order/migrations/0001_initial.py
  models/order/migrations/__init__.py
  models/order/models.py
  models/payment/migrations/0002_alter_payment_method.py
  models/payment/models.py
  models/payment_method/models.py
Labels: to do, enhancement
